kind: Service
apiVersion: v1
metadata:
  name: shortener
  labels:
    app: shortener
spec:
  selector:
    app: shortener
  type: NodePort
  ports:
  - name: nodejs
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32000